

export const HEADER_FIXED = "HEADER_FIXED"
export const HEADER_UNFIXED = "HEADER_UNFIXED"


export const SET_HEADER_FIXED = "SET_HEADDER_FIXED"
export const SET_HEADER_UNFIXED = "SET_HEADDER_UNFIXED"
